version: "3.9"

services:
  client:
    build: .
    volumes:
      - clientvol:/clientdata
    ports:
            - "8181:8181"

    networks:
      - my-network
volumes:
  clientvol:

networks:
  my-network:
    driver: bridge



